image: 'rust:latest'

stages:
  - test
  - doc

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=travelling_salesman">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
